-- ============================================================================
-- Publish Tracker — MySQL schema
--
-- The whole database in one file: tables, links and the triggers that keep
-- them consistent. Ids are UUIDs (CHAR(36)), generated by MySQL.
--
-- Import it into an empty database:
--   phpMyAdmin → select the database → Import → choose this file → Import
--   or: mysql -u root publish_tracker < database/schema.sql
--
-- Needs MySQL 8.0.13+ (expression defaults such as DEFAULT (UUID())).
-- Times are stored in UTC.
-- ============================================================================

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ---------------------------------------------------------------- logins ----

-- Who can sign in. Passwords are stored as bcrypt hashes, never as text.
CREATE TABLE users (
  id            CHAR(36)     NOT NULL DEFAULT (UUID()),
  email         VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name          VARCHAR(255) NULL,
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY users_email_key (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The people apps and releases are assigned to. A login gets one automatically.
CREATE TABLE team_members (
  id         CHAR(36)     NOT NULL DEFAULT (UUID()),
  user_id    CHAR(36)     NULL,
  name       VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NULL,
  active     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY team_members_user_id_key (user_id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------------- clients ----

CREATE TABLE clients (
  id       CHAR(36)     NOT NULL DEFAULT (UUID()),
  ticket   VARCHAR(64)  NOT NULL,
  name     VARCHAR(255) NOT NULL,
  note     TEXT         NULL,
  archived BOOLEAN      NOT NULL DEFAULT FALSE,

  -- Store details shared by every app of the client (Play and App Store)
  play_privacy_url          TEXT         NULL,
  play_delete_account_url   TEXT         NULL,
  play_contact_email        VARCHAR(255) NULL,
  play_listing_email        VARCHAR(255) NULL,
  play_contact_phone        VARCHAR(64)  NULL,
  play_website              TEXT         NULL,
  play_default_language     VARCHAR(128) NULL,
  store_support_url         TEXT         NULL,
  store_marketing_url       TEXT         NULL,
  review_contact_first_name VARCHAR(128) NULL,
  review_contact_last_name  VARCHAR(128) NULL,
  review_contact_phone      VARCHAR(64)  NULL,
  review_contact_email      VARCHAR(255) NULL,

  -- The client form's private link
  intake_token        VARCHAR(128) NULL,
  intake_submitted_at DATETIME(3)  NULL,

  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY clients_ticket_key (ticket),
  UNIQUE KEY clients_intake_token_key (intake_token)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- A client's developer account on one store (one per store).
CREATE TABLE publisher_accounts (
  id           CHAR(36)                            NOT NULL DEFAULT (UUID()),
  client_id    CHAR(36)                            NOT NULL,
  platform     ENUM('play_store', 'app_store')     NOT NULL,
  account_name VARCHAR(255)                        NOT NULL DEFAULT '',
  account_type ENUM('organization', 'personal')    NOT NULL DEFAULT 'organization',
  note         TEXT                                NULL,

  -- How the team gets in, from the client form: invite = they added the
  -- team's email; login = they share the login (password is team-only).
  access_method  ENUM('invite', 'login') NULL,
  access_email   VARCHAR(255)            NULL,
  login_password TEXT                    NULL,

  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY publisher_accounts_client_platform_key (client_id, platform),
  CONSTRAINT publisher_accounts_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One versioned release for one client.
CREATE TABLE releases (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  client_id   CHAR(36)     NOT NULL,
  version     VARCHAR(64)  NOT NULL,          -- 1.1.0, 4.1, 8.4 …
  title       VARCHAR(255) NULL,              -- optional label: "Rental module"
  assigned_to CHAR(36)     NULL,
  note        TEXT         NULL,
  started_on  DATE         NOT NULL DEFAULT (CURRENT_DATE),
  released_on DATE         NULL,              -- set when every app is live
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY releases_client_version_key (client_id, version),
  CONSTRAINT releases_client_id_fkey   FOREIGN KEY (client_id)   REFERENCES clients (id)      ON DELETE CASCADE,
  CONSTRAINT releases_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES team_members (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- The signing keystore a client's apps share. The .jks file itself lives in
-- the uploads folder (UPLOAD_DIR/jks); file_path is relative to it.
CREATE TABLE keystores (
  id         CHAR(36)     NOT NULL DEFAULT (UUID()),
  client_id  CHAR(36)     NOT NULL,
  name       VARCHAR(255) NOT NULL DEFAULT 'Keystore',
  details    TEXT         NULL,               -- key.properties / alias / passwords
  file_path  VARCHAR(512) NULL,
  file_name  VARCHAR(255) NULL,
  note       TEXT         NULL,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  CONSTRAINT keystores_client_id_fkey FOREIGN KEY (client_id) REFERENCES clients (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------------ apps ----

-- One of a client's permanent apps — set up once, submitted every release.
CREATE TABLE products (
  id           CHAR(36)     NOT NULL DEFAULT (UUID()),
  client_id    CHAR(36)     NOT NULL,
  account_id   CHAR(36)     NOT NULL,
  project_name VARCHAR(191) NOT NULL,         -- 6amMart-User-App, StackFood Store …
  app_name     VARCHAR(255) NOT NULL DEFAULT '', -- the store listing name
  keystore_id  CHAR(36)     NULL,
  store_url    TEXT         NULL,
  note         TEXT         NULL,             -- the team's note
  sort_order   INT          NOT NULL DEFAULT 0,
  archived     BOOLEAN      NOT NULL DEFAULT FALSE, -- left out of new releases

  -- Store listing. package_name holds the bundle ID for App Store apps.
  package_name      VARCHAR(255) NULL,
  play_category     VARCHAR(128) NULL,
  short_description VARCHAR(255) NULL,        -- Play limit: 80
  long_description  TEXT         NULL,        -- limit: 4000
  demo_instructions VARCHAR(255) NULL,
  demo_login        VARCHAR(255) NULL,
  demo_password     TEXT         NULL,        -- team-only
  demo_details      TEXT         NULL,
  ios_sku                VARCHAR(255) NULL,
  ios_subtitle           VARCHAR(128) NULL,   -- limit: 30
  ios_keywords           VARCHAR(255) NULL,   -- limit: 100
  ios_promo_text         VARCHAR(512) NULL,   -- limit: 170
  ios_primary_category   VARCHAR(128) NULL,
  ios_secondary_category VARCHAR(128) NULL,
  ios_copyright          VARCHAR(255) NULL,

  -- From the client form: where to publish, image links, the client's note
  publishing_countries TEXT NULL,
  feature_graphic_url  TEXT NULL,
  screenshots_url      TEXT NULL,
  icon_url             TEXT NULL,
  client_note          TEXT NULL,             -- the client's; `note` stays the team's

  -- Store Watch: what the store's public page says. NULL = never checked.
  store_live       BOOLEAN     NULL,
  store_version    VARCHAR(64) NULL,
  store_updated_at DATETIME(3) NULL,
  store_checked_at DATETIME(3) NULL,
  store_error      TEXT        NULL,

  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY products_account_project_key (account_id, project_name),
  CONSTRAINT products_client_id_fkey   FOREIGN KEY (client_id)   REFERENCES clients (id)            ON DELETE CASCADE,
  CONSTRAINT products_account_id_fkey  FOREIGN KEY (account_id)  REFERENCES publisher_accounts (id) ON DELETE CASCADE,
  CONSTRAINT products_keystore_id_fkey FOREIGN KEY (keystore_id) REFERENCES keystores (id)          ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- One app submitted in one release. Its identity (account, names, keystore,
-- store link) always mirrors its product — the triggers below keep it so.
CREATE TABLE apps (
  id                CHAR(36)     NOT NULL DEFAULT (UUID()),
  release_id        CHAR(36)     NOT NULL,
  product_id        CHAR(36)     NOT NULL,
  account_id        CHAR(36)     NOT NULL,
  project_name      VARCHAR(191) NOT NULL,
  app_name          VARCHAR(255) NOT NULL DEFAULT '',
  status            ENUM('ongoing', 'in_review', 'closed_testing', 'rejected', 'production', 'on_hold')
                                 NOT NULL DEFAULT 'ongoing',
  assigned_to       CHAR(36)     NULL,
  build_version     VARCHAR(64)  NULL,         -- 1.0.0+4
  flutter_version   VARCHAR(64)  NULL,
  keystore_id       CHAR(36)     NULL,
  jks               TEXT         NULL,         -- legacy, superseded by keystore_id
  jks_file_path     VARCHAR(512) NULL,         -- legacy
  jks_file_name     VARCHAR(255) NULL,         -- legacy
  store_url         TEXT         NULL,
  note              TEXT         NULL,
  sort_order        INT          NOT NULL DEFAULT 0,
  status_changed_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY apps_release_id_idx (release_id),
  KEY apps_product_id_idx (product_id),
  CONSTRAINT apps_release_id_fkey  FOREIGN KEY (release_id)  REFERENCES releases (id)           ON DELETE CASCADE,
  CONSTRAINT apps_product_id_fkey  FOREIGN KEY (product_id)  REFERENCES products (id)           ON DELETE CASCADE,
  CONSTRAINT apps_account_id_fkey  FOREIGN KEY (account_id)  REFERENCES publisher_accounts (id) ON DELETE CASCADE,
  CONSTRAINT apps_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES team_members (id)       ON DELETE SET NULL,
  CONSTRAINT apps_keystore_id_fkey FOREIGN KEY (keystore_id) REFERENCES keystores (id)          ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- An app's history: created, status changes, notes.
CREATE TABLE app_events (
  id          CHAR(36)     NOT NULL DEFAULT (UUID()),
  app_id      CHAR(36)     NOT NULL,
  kind        VARCHAR(32)  NOT NULL,           -- 'created' | 'status' | 'note'
  from_status ENUM('ongoing', 'in_review', 'closed_testing', 'rejected', 'production', 'on_hold') NULL,
  to_status   ENUM('ongoing', 'in_review', 'closed_testing', 'rejected', 'production', 'on_hold') NULL,
  message     TEXT         NULL,
  actor       VARCHAR(255) NULL,
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY app_events_app_created_idx (app_id, created_at),
  CONSTRAINT app_events_app_id_fkey FOREIGN KEY (app_id) REFERENCES apps (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------- product lines ----

-- A product the team sells (6amMart, StackFood …) and its logo. The logo file
-- lives in the uploads folder (UPLOAD_DIR/logos); logo_path is relative to it.
CREATE TABLE product_lines (
  id         CHAR(36)     NOT NULL DEFAULT (UUID()),
  name       VARCHAR(191) NOT NULL,
  logo_path  VARCHAR(512) NULL,
  sort_order INT          NOT NULL DEFAULT 0,
  created_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY product_lines_name_key (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Which projects (6amMart-User-App …) belong to a product line.
CREATE TABLE product_line_projects (
  id           CHAR(36)     NOT NULL DEFAULT (UUID()),
  line_id      CHAR(36)     NOT NULL,
  project_name VARCHAR(191) NOT NULL,          -- matches products.project_name
  sort_order   INT          NOT NULL DEFAULT 0,
  created_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY product_line_projects_project_key (project_name),
  CONSTRAINT product_line_projects_line_id_fkey FOREIGN KEY (line_id) REFERENCES product_lines (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- -------------------------------------------------------------- triggers ----
-- (updated_at needs none: the columns refresh themselves ON UPDATE.)
--
-- Every trigger stands down while @importing = 1, so loading prepared data
-- (history and team members included) doesn't add them a second time.

DELIMITER $$

-- A release counts as released the day every app in it is live; that date
-- stays put on later edits, and clears if an app goes back.
CREATE PROCEDURE sync_release_released_on(IN target CHAR(36))
BEGIN
  DECLARE total INT DEFAULT 0;
  DECLARE pending INT DEFAULT 0;
  SELECT COUNT(*), COALESCE(SUM(status <> 'production'), 0)
    INTO total, pending
    FROM apps WHERE release_id = target;
  UPDATE releases
     SET released_on = CASE WHEN total > 0 AND pending = 0
                            THEN COALESCE(released_on, CURRENT_DATE) ELSE NULL END
   WHERE id = target;
END$$

-- A product's identity, handed back through OUT parameters (a trigger can pass
-- NEW.* columns to them, which is how it copies the values in).
CREATE PROCEDURE product_identity(
  IN  pid           CHAR(36),
  OUT o_account_id  CHAR(36),
  OUT o_project     VARCHAR(191),
  OUT o_app_name    VARCHAR(255),
  OUT o_keystore_id CHAR(36),
  OUT o_store_url   TEXT
)
BEGIN
  DECLARE n INT DEFAULT 0;
  SELECT COUNT(*) INTO n FROM products WHERE id = pid;
  IF n = 0 THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'That app does not exist.';
  END IF;
  SELECT account_id, project_name, app_name, keystore_id, store_url
    INTO o_account_id, o_project, o_app_name, o_keystore_id, o_store_url
    FROM products WHERE id = pid;
END$$

-- A new login gets its team member, named after the email until renamed.
CREATE TRIGGER users_create_team_member
AFTER INSERT ON users FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    INSERT IGNORE INTO team_members (user_id, name, email)
    VALUES (NEW.id, COALESCE(NULLIF(TRIM(NEW.name), ''), SUBSTRING_INDEX(NEW.email, '@', 1)), NEW.email);
  END IF;
END$$

-- A submission always mirrors its product's identity …
CREATE TRIGGER apps_from_product_ins
BEFORE INSERT ON apps FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    CALL product_identity(NEW.product_id, NEW.account_id, NEW.project_name, NEW.app_name,
                          NEW.keystore_id, NEW.store_url);
  END IF;
END$$

-- … and on every change; a status change also stamps when it happened and
-- goes into the history, credited to the app's assignee.
CREATE TRIGGER apps_before_update
BEFORE UPDATE ON apps FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    CALL product_identity(NEW.product_id, NEW.account_id, NEW.project_name, NEW.app_name,
                          NEW.keystore_id, NEW.store_url);

    IF NOT (NEW.status <=> OLD.status) THEN
      SET NEW.status_changed_at = CURRENT_TIMESTAMP(3);
      INSERT INTO app_events (app_id, kind, from_status, to_status, actor)
      VALUES (NEW.id, 'status', OLD.status, NEW.status,
              (SELECT name FROM team_members WHERE id = NEW.assigned_to));
    END IF;
  END IF;
END$$

-- A new submission: its "created" history entry, and the release's live date.
CREATE TRIGGER apps_after_insert
AFTER INSERT ON apps FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    INSERT INTO app_events (app_id, kind, to_status, message, actor)
    VALUES (NEW.id, 'created', NEW.status, 'App added',
            (SELECT name FROM team_members WHERE id = NEW.assigned_to));
    CALL sync_release_released_on(NEW.release_id);
  END IF;
END$$

CREATE TRIGGER apps_after_update
AFTER UPDATE ON apps FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    CALL sync_release_released_on(NEW.release_id);
    IF NOT (NEW.release_id <=> OLD.release_id) THEN
      CALL sync_release_released_on(OLD.release_id);
    END IF;
  END IF;
END$$

CREATE TRIGGER apps_after_delete
AFTER DELETE ON apps FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    CALL sync_release_released_on(OLD.release_id);
  END IF;
END$$

-- Editing an app (product) updates every submission of it.
CREATE TRIGGER products_sync_apps
AFTER UPDATE ON products FOR EACH ROW
BEGIN
  IF COALESCE(@importing, 0) = 0 THEN
    IF NOT (NEW.account_id   <=> OLD.account_id
        AND NEW.project_name <=> OLD.project_name
        AND NEW.app_name     <=> OLD.app_name
        AND NEW.keystore_id  <=> OLD.keystore_id
        AND NEW.store_url    <=> OLD.store_url) THEN
      UPDATE apps
         SET account_id   = NEW.account_id,
             project_name = NEW.project_name,
             app_name     = NEW.app_name,
             keystore_id  = NEW.keystore_id,
             store_url    = NEW.store_url
       WHERE product_id = NEW.id;
    END IF;
  END IF;
END$$

DELIMITER ;
